# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: glimmer-cw-nebula 2.4.3.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "glimmer-cw-nebula".freeze
  s.version = "2.4.3.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Andy Maleh".freeze]
  s.date = "2021-03-10"
  s.description = "The [Nebula Project](https://www.eclipse.org/nebula/) is a collection of enterprise-grade high-quality SWT (Standard Widget Toolkit) custom widgets, which are made available for use with [Glimmer DSL for SWT](https://github.com/AndyObtiva/glimmer-dsl-swt) in this Ruby gem.".freeze
  s.email = "andy.am@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "LICENSE.txt",
    "README.md",
    "VERSION",
    "glimmer-cw-nebula.gemspec",
    "lib/glimmer-cw-nebula.rb",
    "vendor/nebula/org.eclipse.nebula.cwt_1.1.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.effects.stw_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.paperclips.core_2.1.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.paperclips.widgets_2.1.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.badgedlabel_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.carousel_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.cdatetime_1.5.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.chips_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.compositetable_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.ctreecombo_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.floatingtext_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.fontawesome_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.gallery_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.ganttchart_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.geomap_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.grid_1.1.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.led_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.nebulaslider_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.opal.breadcrumb_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.opal.calculator_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.opal.checkboxgroup_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.opal.columnbrowser_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.opal.commons_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.opal.dialog_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.opal.duallist_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.opal.header_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.opal.heapmanager_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.opal.horizontalspinner_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.opal.launcher_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.opal.logindialog_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.opal.multichoice_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.opal.notifier_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.opal.panels_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.opal.preferencewindow_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.opal.promptsupport_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.opal.propertytable_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.opal.rangeslider_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.opal.roundedtoolbar_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.opal.starrating_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.opal.switchbutton_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.opal.textassist_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.opal.tipoftheday_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.opal.titledseparator_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.oscilloscope_1.4.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.passwordrevealer_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.pgroup_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.progresscircle_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.pshelf_1.1.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.richtext_1.4.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.roundedswitch_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.segmentedbar_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.splitbutton_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.stepbar_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.tablecombo_1.2.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.xviewer.core_1.0.0.202011020719.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.xviewer_1.1.0.202011020719.jar"
  ]
  s.homepage = "http://github.com/AndyObtiva/glimmer-cw-nebula".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.0.6".freeze
  s.summary = "Nebula - Glimmer Custom Widget".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<glimmer-dsl-swt>.freeze, [">= 4.18.0.0", "< 5.0.0.0"])
      s.add_development_dependency(%q<rspec>.freeze, ["~> 3.5.0"])
      s.add_development_dependency(%q<juwelier>.freeze, ["= 2.4.9"])
      s.add_development_dependency(%q<warbler>.freeze, ["= 2.0.5"])
      s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
    else
      s.add_dependency(%q<glimmer-dsl-swt>.freeze, [">= 4.18.0.0", "< 5.0.0.0"])
      s.add_dependency(%q<rspec>.freeze, ["~> 3.5.0"])
      s.add_dependency(%q<juwelier>.freeze, ["= 2.4.9"])
      s.add_dependency(%q<warbler>.freeze, ["= 2.0.5"])
      s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<glimmer-dsl-swt>.freeze, [">= 4.18.0.0", "< 5.0.0.0"])
    s.add_dependency(%q<rspec>.freeze, ["~> 3.5.0"])
    s.add_dependency(%q<juwelier>.freeze, ["= 2.4.9"])
    s.add_dependency(%q<warbler>.freeze, ["= 2.0.5"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
  end
end

